name: torch10
channels:
  - pytorch
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argh=0.26.2=py39h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py39hdd57654_1
  - brokenaxes=0.4.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.14.6=py39h400218f_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.0.2=pyhd3eb1b0_0
  - cryptography=3.4.8=py39hd23ed53_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.78.0=h1ccaba5_0
  - cycler=0.10.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - docopt=0.6.2=py_1
  - et_xmlfile=1.0.1=py_1001
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h6c09931_0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h5ab3b9f_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - git=2.32.0=pl5262hc120c5b_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.18=pyhd3eb1b0_1
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gql=0.1.0=py_0
  - graphite2=1.3.13=h58526e2_1001
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.6.0=py39ha0f2276_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jdcal=1.4.1=py_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kaleido-core=0.2.1=h3644ca4_0
  - kiwisolver=1.3.1=py39h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h295c915_1
  - mathjax=2.7.7=0
  - matplotlib=3.3.4=py39h06a4308_0
  - matplotlib-base=3.3.4=py39h62a2d02_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpfr=4.1.0=h9202a9a_1
  - mpi=1.0=openmpi
  - mpi4py=3.0.3=py39hc649577_4
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - nvidia-ml=7.352.0=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=hb52868f_1
  - openmpi=4.0.2=hb1b8bf9_1
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1l=h7f98852_0
  - pandas=1.2.5=py39h295c915_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pcre2=10.35=h14c3975_1
  - perl=5.26.2=h14c3975_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - pipreqs=0.4.10=py_0
  - pixman=0.40.0=h36c2ea0_0
  - plotly=5.4.0=py_0
  - poppler=0.81.0=h01f5e8b_2
  - poppler-data=0.4.11=hd8ed1ab_0
  - promise=2.3=py39h06a4308_0
  - protobuf=3.17.2=py39h295c915_0
  - psutil=5.8.0=py39h27cfd23_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.6=h49503c6_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=5.4.1=py39h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py39ha9443f7_0
  - scipy=1.7.1=py39h292c36d_2
  - seaborn=0.11.1=pyhd3eb1b0_0
  - sentry-sdk=1.4.3=pyhd8ed1ab_0
  - setuptools=58.0.4=py39h06a4308_0
  - shortuuid=1.0.1=py39hf3d152e_4
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - subprocess32=3.5.4=py_1
  - tabulate=0.8.9=py39h06a4308_0
  - tenacity=8.0.1=py39h06a4308_0
  - texlive-core=20180414=hc8d0b01_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.1=py39_cu113
  - torchvision=0.11.2=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wandb=0.12.1=pyhd8ed1ab_0
  - watchdog=0.10.4=py39hf3d152e_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!157.20191217=h7b6447c_0
  - xlsxwriter=3.0.2=pyhd8ed1ab_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarg=0.1.9=py_1
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=haebb681_0
prefix: /home/debora/utils/anaconda3/envs/torch10
